/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AAlert: typeof import('ant-design-vue/es')['Alert']
    AButton: typeof import('ant-design-vue/es')['Button']
    ACollapse: typeof import('ant-design-vue/es')['Collapse']
    ACollapsePanel: typeof import('ant-design-vue/es')['CollapsePanel']
    ADrawer: typeof import('ant-design-vue/es')['Drawer']
    AInput: typeof import('ant-design-vue/es')['Input']
    AInputNumber: typeof import('ant-design-vue/es')['InputNumber']
    AModal: typeof import('ant-design-vue/es')['Modal']
    APopconfirm: typeof import('ant-design-vue/es')['Popconfirm']
    AppButton: typeof import('./src/components/AppButton.vue')['default']
    AppDrawer: typeof import('./src/components/AppDrawer.vue')['default']
    AppForm: typeof import('./src/components/AppForm.vue')['default']
    AppFormModal: typeof import('./src/components/AppFormModal.vue')['default']
    AppModal: typeof import('./src/components/AppModal.vue')['default']
    AppTable: typeof import('./src/components/AppTable.vue')['default']
    AProgress: typeof import('ant-design-vue/es')['Progress']
    ASelect: typeof import('ant-design-vue/es')['Select']
    ASpace: typeof import('ant-design-vue/es')['Space']
    ASwitch: typeof import('ant-design-vue/es')['Switch']
    ATag: typeof import('ant-design-vue/es')['Tag']
    CodeEditor: typeof import('./src/components/CodeEditor.vue')['default']
    ComposeEditorModal: typeof import('./src/components/ComposeEditorModal.vue')['default']
    ContainerExecModal: typeof import('./src/components/ContainerExecModal.vue')['default']
    ContainerLogsModal: typeof import('./src/components/ContainerLogsModal.vue')['default']
    CredentialFormModal: typeof import('./src/components/CredentialFormModal.vue')['default']
    RegistryModal: typeof import('./src/components/RegistryModal.vue')['default']
    RouteLogsModal: typeof import('./src/components/RouteLogsModal.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
